CREATE TABLE users (
   id INT AUTO_INCREMENT PRIMARY KEY,
   name varchar(255) NOT NULL,
   email varchar(255) NOT NULL UNIQUE,
   password VARCHAR(255) NOT NULL,
   role ENUM('customer', 'admin') DEFAULT 'customer',
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);